name: CI

on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm audit --audit-level=high
      - run: npm ci
      - run: npm run test
        env:
          FURY_AUTH: ${{ secrets.FURY_AUTH_PULL }}

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FURY_AUTH: ${{ secrets.FURY_AUTH_PUSH }}
        run: npm run release
